const subjects = [
  "Quick question", "Following up", "Wanted to check in", "Thoughts on this?",
  "Quick sync?", "One thing I noticed", "Can we connect?", "Brief question for you",
  "Checking in", "Hope you're doing well", "Touching base", "A thought for you",
  "Circling back", "Just a heads up", "Something came to mind", "Any updates?",
  "Quick note", "Catching up", "Something interesting", "A quick ask",
  "Worth a look?", "Curious about something", "Friendly ping", "One more thing",
  "In case you missed it", "Thought of you", "Idea for you", "Got a sec?",
  "Small favor", "Loop back", "Random thought", "Quick favor",
  "Something cool", "FYI", "Nudge", "Ping",
  "Re: our chat", "Follow-up thought", "Another idea", "Checking back",
  "Hey again", "One quick thing", "Before I forget", "On my mind",
  "Wanted your take", "Your opinion?", "A suggestion", "Mind if I ask?",
  "Would love input", "Short question", "Two-minute ask", "Real quick",
  "Popping in", "Dropping a line", "Brief note", "Thought this was cool",
  "Sharing something", "Your thoughts?", "Quick idea", "Brainstorm?",
  "Let's chat", "Interesting find", "Saw this today", "Worth discussing?",
  "Quick update", "Small update", "News from my end", "Progress note",
  "Status check", "Where are we?", "Moving forward", "Next steps?",
  "Planning ahead", "Scheduling note", "Time sensitive", "When works?",
  "Calendar check", "Availability?", "Meeting follow-up", "Post-meeting note",
  "Action items", "Recap", "Summary", "Highlights",
  "Key takeaway", "Important note", "Heads up on this", "PSA",
  "Don't forget", "Reminder", "Gentle reminder", "Just flagging",
  "For your review", "Feedback request", "Draft for you", "Eyes on this?",
  "Review needed", "Approval needed", "Sign-off request", "Final check",
  "Almost there", "Wrapping up", "Final thoughts", "Closing the loop",
  "Last thing", "One last ask", "Before we wrap", "End of week note",
]

const openers = [
  "Hey — hope your week's going well.",
  "Hi there, just wanted to reach out.",
  "Hope you're having a good day.",
  "Hey! Quick message for you.",
  "Hi — I know you're busy, so I'll keep this short.",
  "Hey, hope things are going smoothly on your end.",
  "Hi! Just popping in with a quick note.",
  "Hope your Monday is off to a good start.",
  "Hey there — long time no chat!",
  "Hi, hope I'm not catching you at a bad time.",
  "Hey! Been meaning to reach out.",
  "Hi — just a friendly ping.",
  "Hope the week is treating you well so far.",
  "Hey, thought I'd drop you a quick line.",
  "Hi there — wanted to loop back on something.",
  "Hey! Hope you had a great weekend.",
  "Hi, quick question for you if you have a sec.",
  "Hey — circling back on our earlier conversation.",
  "Hi! Saw something that made me think of you.",
  "Hope all is well on your side.",
  "Hey, just checking in real quick.",
  "Hi there — no pressure, just touching base.",
  "Hey! Got a minute? Nothing urgent.",
  "Hi — wanted to float something by you.",
  "Hope your day is going well so far.",
  "Hey, quick thought I wanted to share.",
  "Hi! Just a brief note from my end.",
  "Hey there — hope things are good.",
  "Hi, just following up on something small.",
  "Hey! Dropping a quick message your way.",
  "Hi — hope you're doing great this week.",
  "Hey, I've got a quick idea to run past you.",
  "Hi there! Just wanted to check in briefly.",
  "Hey — hope I'm not interrupting anything.",
  "Hi, thought of you while working on something.",
  "Hey! Quick ping — nothing major.",
  "Hi there — how's everything going?",
  "Hey, just a heads up on something.",
  "Hi! Wanted to share a thought real quick.",
  "Hope you're having a productive week.",
  "Hey there — short one for you today.",
  "Hi, just reaching out with a small ask.",
  "Hey! Hope you're keeping well.",
  "Hi — figured I'd shoot you a message.",
  "Hope your inbox isn't too crazy today.",
  "Hey, quick note before I forget.",
  "Hi there — appreciate you reading this.",
  "Hey! Just a casual check-in.",
  "Hi, hope you've got a moment.",
  "Hey — wanted to keep you in the loop.",
  "Hi! Thought this was worth mentioning.",
  "Hope everything's on track for you.",
  "Hey there — friendly reminder from me.",
  "Hi, just nudging you on something.",
  "Hey! Hope the day is going well.",
  "Hi — one small thing to mention.",
  "Hope you're finding some good momentum today.",
  "Hey, just wanted to reconnect briefly.",
  "Hi there — been thinking about our last chat.",
  "Hey! Quick follow-up from earlier.",
  "Hi, hope you're crushing it this week.",
  "Hey — just a lightweight note for you.",
  "Hi! Didn't want to let this slip through the cracks.",
  "Hope your schedule isn't too packed today.",
  "Hey there — thought I'd reach out.",
  "Hi, just a short message to stay connected.",
  "Hey! Wanted to get your perspective on something.",
  "Hi — hope the week's wrapping up nicely.",
  "Hope you're doing well! Quick message incoming.",
  "Hey, just wanted to stay on your radar.",
  "Hi there — sending good vibes and a quick note.",
  "Hey! Hope I can grab a minute of your time.",
  "Hi, thought I'd send a quick update.",
  "Hey — nothing urgent, just touching base.",
  "Hi! Hope you've been well.",
  "Hope your projects are coming along nicely.",
  "Hey there — just dropping in briefly.",
  "Hi, quick message before the week ends.",
  "Hey! Wanted to pass something along.",
  "Hi — just a small thing on my mind.",
  "Hope you're enjoying the day so far.",
  "Hey, wanted to make sure we're synced up.",
  "Hi there — just a gentle follow-up.",
  "Hey! No rush on this, but wanted to share.",
  "Hi, hope you can spare a quick moment.",
  "Hey — just keeping the conversation going.",
  "Hi! Wanted to circle back real quick.",
  "Hope the coffee is strong and the inbox is light.",
  "Hey there — thought of something relevant to you.",
  "Hi, just making sure this didn't get buried.",
  "Hey! Quick one for you.",
  "Hi — hope you're having a solid week.",
  "Hope things are chill on your end.",
  "Hey, just a micro update for you.",
  "Hi there — wanted to keep this top of mind.",
  "Hey! Brief message, promise.",
  "Hi, hope you're in a good headspace today.",
  "Hey — just shooting a quick note over.",
  "Hi! Wanted to keep you posted.",
  "Hope you're wrapping up the week strong.",
]

const bodies = [
  "I was looking into some strategies and thought this might align with what you're working on.",
  "Came across an approach that reminded me of our discussion. Curious if it clicks for you too.",
  "I've been researching some ideas in this space and figured you might have a perspective.",
  "There's something I've been mulling over and I'd genuinely appreciate a second opinion.",
  "I noticed a few trends recently that seem relevant to what we talked about.",
  "Was doing some reading and stumbled on something that might be useful for your workflow.",
  "I've been experimenting with a new process and thought you might find it interesting.",
  "Something came up in a meeting that made me think of our earlier conversation.",
  "I've been digging into this topic and wanted to see if you've encountered the same patterns.",
  "There's a resource I found that I think could save you some time.",
  "I was reviewing some notes and realized there's an angle we didn't fully explore.",
  "Been thinking about optimization lately and had an idea worth bouncing off you.",
  "I came across a case study that's surprisingly relevant to what you're building.",
  "There's a methodology I've been testing that seems promising — thought of you.",
  "I saw an interesting thread online that connects to what you mentioned last time.",
  "Been working on something adjacent to your project and noticed some overlap.",
  "I had a conversation recently that sparked an idea I think you'd appreciate.",
  "There's a tool I started using that might streamline some of your processes.",
  "I've been reflecting on our last exchange and wanted to add one more thought.",
  "Something in the news caught my eye and made me think of your work.",
  "I was brainstorming solutions and one of them feels like it could work for you too.",
  "There's a pattern I've noticed across a few projects that might be worth discussing.",
  "I ran into a challenge similar to what you described — here's what worked for me.",
  "Been exploring some alternatives and found one that surprised me.",
  "I was looking at some data and thought the findings might interest you.",
  "There's a framework I've been studying that could apply nicely to your situation.",
  "I noticed something in our industry that's shifting and figured you'd want to know.",
  "Been doing some competitive research and found a few insights worth sharing.",
  "I was mapping out some workflows and thought of a potential improvement for yours.",
  "There's an opportunity I spotted that aligns with what you're focused on.",
  "I've been connecting dots between a few ideas and one thread leads to you.",
  "Was chatting with someone in the field and your name came up — in a good way.",
  "I stumbled on a best practice that contradicts conventional wisdom. Intriguing.",
  "There's a webinar recap I read that had some genuinely useful takeaways.",
  "I was auditing my own process and found a gap that you might have solved.",
  "Been thinking about scalability and had a thought that might resonate with you.",
  "I came across a benchmark that puts things in perspective. Worth a glance.",
  "There's a shift happening in our space that I think deserves more attention.",
  "I was prototyping something and realized it overlaps with your recent work.",
  "Been revisiting some earlier assumptions and wanted to get your updated take.",
  "I noticed an opportunity to collaborate on something small but impactful.",
  "There's a question I keep coming back to and I think you might have the answer.",
  "I was looking at things from a different angle and it opened up new possibilities.",
  "Been paying attention to user behavior and spotted something counterintuitive.",
  "I had an insight while working on a different project that applies here.",
  "There's a conversation happening in the community that I think you should weigh in on.",
  "I was simplifying a process and found an approach that's surprisingly effective.",
  "Been thinking about long-term strategy and had an idea that might fit your roadmap.",
  "I came across some feedback that aligns with the direction you're heading.",
  "There's a technique I learned recently that could complement your current setup.",
  "I was organizing my resources and found something I'd bookmarked for you.",
  "Been experimenting with automation and found a quick win worth sharing.",
  "I noticed a gap in the market that seems tailor-made for what you do.",
  "There's a recent development that could change how we think about this.",
  "I was stress-testing an idea and thought your perspective would strengthen it.",
  "Been looking at success stories and found patterns that might inform your approach.",
  "I came across an integration that could save a lot of manual work.",
  "There's a mental model I've adopted that's been incredibly clarifying.",
  "I was exploring partnerships and thought of a potential synergy between us.",
  "Been analyzing some results and found something that challenges my assumptions.",
  "I noticed a recurring theme in client feedback that might affect your work too.",
  "There's a simplification I made that improved outcomes dramatically.",
  "I was thinking about risk mitigation and came up with a lightweight approach.",
  "Been studying some emerging trends and one stands out as particularly relevant.",
  "I came across a contrarian take that actually makes a lot of sense.",
  "There's a workflow hack I discovered that I haven't seen many people using.",
  "I was reviewing performance metrics and noticed something worth investigating.",
  "Been mapping dependencies and found an area where we could reduce friction.",
  "I noticed a best practice evolving and thought you'd want to stay ahead of it.",
  "There's a connection between two ideas that I think creates real value.",
  "I was doing a retrospective and identified a lesson that applies broadly.",
  "Been focused on efficiency gains and found one that's almost embarrassingly simple.",
  "I came across a perspective shift that reframed the whole problem for me.",
  "There's a small change I made that had outsized impact — reminded me of your approach.",
  "I was reviewing our alignment and spotted an area where we could do more together.",
  "Been looking at this from the end-user perspective and it changes everything.",
  "I noticed something subtle that could become a major advantage if acted on early.",
  "There's a principle I've been applying that keeps proving useful in new contexts.",
  "I was comparing approaches and found one that balances speed and quality well.",
  "Been collecting examples of what works and this one really stood out.",
  "I came across an insight from an unexpected source — sometimes the best ones are.",
  "There's a lesson from a different industry that transfers perfectly to ours.",
  "I was thinking about what's next and had a thought I'd love your reaction to.",
  "Been observing patterns and one in particular keeps showing up — curious if you see it too.",
  "I noticed a blind spot in my own thinking and wonder if it's a common one.",
  "There's something I've been meaning to ask your opinion on.",
  "I was thinking about how to make things simpler and had a small breakthrough.",
  "Been focusing on what to stop doing as much as what to start — interesting exercise.",
  "I came across a data point that surprised me. Wondering if it surprises you too.",
  "There's an approach I initially dismissed but it's growing on me.",
  "I was looking for patterns of failure and found a few that are easy to avoid.",
  "Been paying closer attention to timing and it seems to matter more than I thought.",
  "I noticed a way to reduce complexity that doesn't sacrifice capability.",
  "There's a question I think we should both be asking ourselves more often.",
  "I was exploring edge cases and found one that's actually quite common.",
  "Been thinking about resilience and had an idea that builds on your earlier point.",
  "I came across something that challenged my mental model in a useful way.",
  "There's a subtle shift in priorities happening that I think deserves a conversation.",
  "I was recalibrating my goals and thought this adjustment might help you too.",
  "Been sitting with a problem and finally had a clarity moment worth sharing.",
]

const closers = [
  "Let me know what you think when you get a chance.",
  "No rush — just wanted to put this on your radar.",
  "Happy to discuss further if it's of interest.",
  "Would love to hear your thoughts.",
  "Totally understand if now's not the right time.",
  "Feel free to ignore if this doesn't resonate.",
  "Whenever you have a moment, I'd appreciate your take.",
  "No pressure — just thought it was worth mentioning.",
  "Let me know if you'd like to dig deeper into this.",
  "Curious to hear your perspective when you're free.",
  "Take your time — just planting the seed.",
  "Happy to elaborate if anything sparks your interest.",
  "Let me know if this aligns with where you're headed.",
  "No expectations — just sharing in case it's useful.",
  "Would be great to get your input if you have a sec.",
  "Shoot me a reply whenever works for you.",
  "Open to hearing your thoughts either way.",
  "Just wanted to share — do with it what you will.",
  "If this resonates, let's set up a time to talk.",
  "No worries if you're swamped — it can wait.",
  "Hoping to hear back but totally understand if not.",
  "Let me know your thoughts — even a quick reaction helps.",
  "Would value your two cents on this.",
  "Ping me back if you'd like to explore this more.",
  "If you have bandwidth, I'd love a quick chat about it.",
  "Just wanted to keep you in the loop — no action needed.",
  "Whenever you have a quiet moment, I'd welcome your take.",
  "Reply at your leisure — no urgency here.",
  "If this is relevant to you, let's connect.",
  "Thanks for reading — let me know either way.",
  "Standing by if you want to riff on this.",
  "Let me know if I should send more details.",
  "Happy to hop on a call if easier.",
  "Just flagging it — you know best if it's worth pursuing.",
  "Would be cool to hear your angle on this.",
  "Take what's useful and leave the rest.",
  "Let me know if you want me to dig further.",
  "Always appreciate your perspective on these things.",
  "Hit me back when the timing feels right.",
  "No reply needed unless something clicks.",
  "Open to continuing this thread whenever.",
  "Let me know if this sparks any ideas on your end.",
  "Would love to brainstorm if you're up for it.",
  "Sharing because I think it might help — no strings attached.",
  "If you've got 2 minutes, I'd love your reaction.",
  "Just wanted to plant the idea — let it marinate.",
  "Let me know if I'm off base here.",
  "Hope this is helpful — reach out anytime.",
  "Looking forward to hearing your thoughts, no rush.",
  "Whenever you're ready, I'm here to discuss.",
  "Feel free to sit on this and come back to it later.",
  "If this doesn't land, no worries at all.",
  "Just thought you should know — do as you see fit.",
  "Would appreciate any quick feedback you might have.",
  "Standing by for your thoughts when you have them.",
  "Take a look when you can and let me know.",
  "If it makes sense to you, let's move forward.",
  "Just sharing — no obligation whatsoever.",
  "Ping me if you want to chat through it live.",
  "Let me know what resonates and what doesn't.",
  "Hope this adds value — feedback welcome.",
  "Would love to sync up on this if you're interested.",
  "Let me know and I can send over more context.",
  "Happy to answer any questions this might raise.",
  "Shoot me your thoughts when you get a break.",
  "No need to respond right away — just whenever.",
  "If this is useful, I have more where it came from.",
  "Just keeping the dialogue open — respond anytime.",
  "Let me know if you'd like to collaborate on this.",
  "Appreciate you considering it — talk soon either way.",
  "Would mean a lot to get your honest reaction.",
  "Feel free to push back if you see it differently.",
  "Let me know if I should elaborate or keep it brief.",
  "Reply when the moment strikes — no deadline.",
  "If you want to riff on this, I'm game.",
  "Just putting it out there — curious what you think.",
  "Let me know if we should schedule time to discuss.",
  "Hope this helps — always happy to trade ideas.",
  "Take a look and tell me what stands out to you.",
  "Let me know if you see this the same way.",
  "If it's a good fit, let's talk next steps.",
  "No worries if it's not the right time — just wanted to share.",
  "Send me your thoughts whenever you get to it.",
  "If you want to bounce ideas, I'm around.",
  "Let me know how I can help or if you need more info.",
  "Just throwing it out there for you to consider.",
  "Hit me up if you want to unpack this further.",
  "Would love to collaborate if the interest is mutual.",
  "Let me know where you land on this.",
  "No strings — just thought it was worth flagging.",
  "Shoot me a note when you've had a chance to think it over.",
  "Happy to adjust my thinking based on your feedback.",
  "If this doesn't fit, just say the word — no hard feelings.",
  "Let me know what works for you and we'll go from there.",
  "Excited to hear your take when you're ready.",
  "Just keeping things moving — reply when you can.",
  "If anything here is off, I'd rather you tell me.",
  "Let me know and I'll send over what I have.",
  "Cheers — talk soon hopefully.",
  "Let me know what direction feels right.",
  "Open to whatever makes sense for you.",
]

const replies = [
  "Thanks for reaching out! Let me look into this and get back to you.",
  "Appreciate you following up. I'll review and circle back soon.",
  "Good timing — was just thinking about this. Let me gather my thoughts.",
  "Thanks! This is on my radar. Will respond properly when I have a moment.",
  "Noted — appreciate you keeping me in the loop.",
  "Hey, thanks for this! Definitely interested — let me take a closer look.",
  "Really appreciate you sharing. I'll dig into it this week.",
  "Thanks for the nudge — I'll get back to you with more detail soon.",
  "Got it! Let me review and I'll follow up.",
  "This is great timing actually. Let me think on it and reply properly.",
  "Thanks for putting this on my radar. Will loop back shortly.",
  "Appreciate the heads up — I'll take a look and let you know.",
  "Nice, thanks for sharing! Curious to explore this further.",
  "Got it, thanks! I'll carve out some time to go through this.",
  "Really helpful — thanks. Let me process and get back to you.",
  "Thanks! This aligns with something I've been thinking about too.",
  "Appreciate you reaching out. Let me sit with this and respond soon.",
  "Hey! Good to hear from you. Let me review and come back with thoughts.",
  "Thanks for flagging this — definitely worth a deeper look.",
  "Noted with thanks. I'll follow up once I've had a chance to review.",
  "This is interesting — let me take some time with it.",
  "Thanks for the ping! I'll circle back when I've had a chance to think.",
  "Appreciate it! Let me check a few things and get back to you.",
  "Good stuff — thanks for sending this over. More soon.",
  "Thanks for keeping me in the loop. Will respond in detail shortly.",
  "Hey, thanks! This is definitely worth exploring. Give me a bit.",
  "Great point — let me mull it over and reply properly.",
  "Received — thanks! I'll get back to you soon.",
  "Thanks for thinking of me! Let me review and share my take.",
  "Appreciate the follow-up. I'll look into this and circle back.",
  "Thanks! Flagging this for a proper response when I have more time.",
  "Good to hear from you — let me digest this and reply.",
  "Thanks for sharing your thoughts. I'll reflect and respond soon.",
  "Got this — appreciate it. Let me get back to you with a proper reply.",
  "Thanks! Really appreciate you taking the time. More from me soon.",
  "This resonates — let me think about it and come back to you.",
  "Appreciate the thoughtfulness here. Let me reply in more detail soon.",
  "Thanks for this! Saving it to respond properly when I'm at my desk.",
  "Hey, great timing! Let me look into it and follow up.",
  "Thanks — this is helpful. I'll get back to you shortly.",
  "Really appreciate this. Let me gather my thoughts and respond.",
  "Good stuff! Let me take a look and circle back.",
  "Thanks for the heads up — very relevant. More soon.",
  "Appreciate you sharing! I'll review and get back with feedback.",
  "Thanks! This is exactly what I needed. Let me respond properly soon.",
  "Got it — thanks for reaching out. Will reply in detail shortly.",
  "Hey, thanks for this! Makes me think. Let me get back to you.",
  "Appreciate the note. I'll sit with this and follow up.",
  "Thanks for putting this together. Let me review and respond.",
  "This is great — appreciate you flagging it. More from me soon.",
  "Thanks! I want to give this a proper response. Stand by.",
  "Good to hear from you! Let me check on a few things first.",
  "Thanks for the reminder — I'll get back to you on this.",
  "Appreciate it! Let me sync with my schedule and reply.",
  "Thanks for looping me in. I'll dig in and respond soon.",
  "Hey! Good point — let me think about this more carefully.",
  "Thanks for sending this over. I'll reply with more substance soon.",
  "Got it, much appreciated! Let me follow up properly.",
  "Thanks! Definitely aligns with my thinking. More soon.",
  "Appreciate the ping — I'll get back to you when I've processed this.",
  "Thanks for raising this. Let me review and share my thoughts.",
  "Hey, appreciate you! Let me look at this and circle back.",
  "Good note — thanks. I'll respond when I've had time to reflect.",
  "Thanks! Let me take this in and get back to you.",
  "Appreciate the outreach. Standing by to reply more fully soon.",
  "Thanks — really good timing on this. Let me review.",
  "Got it! Appreciate you thinking of me. More soon.",
  "Thanks for the context. Let me process and reply.",
  "Hey! This is great. Give me a bit and I'll come back with thoughts.",
  "Thanks for sharing — this is on my list to respond to properly.",
  "Appreciate it! Let me take a beat and get back to you.",
  "Thanks! Really valuable. I'll follow up soon.",
  "Good timing — appreciate it. Let me reply with more soon.",
  "Thanks for the note! I'll take a closer look and circle back.",
  "Got this — appreciate the thought. More from me shortly.",
  "Hey, thanks! Let me review and I'll shoot you a proper reply.",
  "Appreciate the heads up! I'll look into it and follow up.",
  "Thanks for connecting on this. Let me respond more fully soon.",
  "Good stuff — appreciate you sharing. I'll get back to you.",
  "Thanks! Making a note to follow up on this properly.",
  "Hey! Appreciate the message. Let me review and reply.",
  "Thanks for bringing this to my attention. More soon.",
  "Got it — thanks for the follow-up! I'll circle back shortly.",
  "Really appreciate this. Let me take some time and respond.",
  "Thanks for keeping this on my radar. Reply incoming soon.",
  "Hey, this is helpful — thanks! Let me get back to you.",
  "Appreciate the thought! I'll review and respond with my take.",
  "Thanks! Good to reconnect. Let me come back with a fuller reply.",
  "Got it, thanks! Let me look at this when I have a clear head.",
  "Appreciate you reaching out — I'll respond properly soon.",
  "Thanks for the quick note! Let me sit with it and reply.",
  "Hey! This is timely. Let me review and circle back.",
  "Thanks — appreciate the ping. I'll follow up shortly.",
  "Good to hear from you! Let me think and respond.",
  "Thanks for this — really appreciate it. More from me soon.",
  "Got it! Let me take a look and get back to you.",
  "Appreciate the note — I'll respond with my thoughts soon.",
  "Thanks for sharing this! I'll review and circle back.",
  "Hey, appreciate it! Let me digest and reply properly.",
  "Thanks! Saving this to give it the attention it deserves.",
  "Appreciate the follow-up — I'll get back to you soon with more.",
]

function pick(arr: string[]): string {
  return arr[Math.floor(Math.random() * arr.length)]
}

export function generateEmail() {
  return {
    subject: pick(subjects),
    body: `${pick(openers)}\n\n${pick(bodies)}\n\n${pick(closers)}`,
    reply: pick(replies),
  }
}
